### PR TITLE
Project 8: Add Devise.

### PR DESCRIPTION
**Pull request by er-contreras**
- Remove current_user method in ApplicationController, devise will provide us with one.
  - Install and setup devise.
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- Modify the views in devise for registration and login to match the wireframes and your styling.

## Note 

We use a mailcatcher to confirm the email if you not already install it. [mailcatcher](https://mailcatcher.me/) 

## This is our last change so be kind 🙏🏼

this were our last PR and reviews https://github.com/tiagorahal/blog-app/pull/11 but we decided to creat a new PR from different Repo

### CODE REVIEW

**Review by SajjadAhmad14 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Erick, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL
## Please always use the same PR for re-review which was used in the first review.
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by descholar-ceo — COMMENTED** [review]
Hi @eri8-9 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is already approved and merged, we would require you to submit an open PR which contains changes of your work.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tiagorahal** [comment]
## Hello dear reviewer.
###  The dashboard is with some problem updating my status with one of my coding partners regarding the project status, this milestone I did with him as you can see in this print(below).
### I would like to ask you to mark as completed this milestone for me so I can continue with the project on my side, as the only milestone where this happened was this one.
### Thank you so much for your consideration.
image

**Review by henatan99 — COMMENTED** [review]
Hi @eri8-9 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the dev team is dealing with the issues raised. Unfortunately, I don't have the mandate to review it as the dev team is still going to take action about it. Please, don't worry it will be handled well, and wait until the dev team reaches back to you. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
